# .scrutinizer.yml

build:

    dependencies:
        before:
            - rm composer.lock

    services:
        mysql: 5.7        

    tests:
        before:
            - mysql -h 127.0.0.1 -u root -e 'create database test'
            - mysql -u root test < tests/mysql_database.sql.txt

        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'

    nodes:

        php72:
            environment:
                php: 7.2

        php73:
            environment:
                php: 7.3


checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*

